import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>The KJ Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          The KJ Store
        </div>
        <div className={styles.container}>
          <a href="">
            <div className={styles.card}>
              <Image alt='anya-image' src='/images/anya.jpg' width={200} height={100} />
              <h2>Anya</h2>
              <span>What is this</span>
              <p>Description of the product here</p>
            </div>
          </a>
          <a href="">
            <div className={styles.card}>
              <Image alt='damian-image' src='/images/damian.jpg' width={200} height={100} />
              <h2>Damian</h2>
              <span>What is this</span>
              <p>Description of the product here</p>
            </div>
          </a>
          <a href="">
            <div className={styles.card}>
              <h2>Title here</h2>
              <span>What is this</span>
              <p>Description of the product here</p>
            </div>
          </a>
          <a href="">
            <div className={styles.card}>
              <h2>Title here</h2>
              <span>What is this</span>
              <p>Description of the product here</p>
            </div>
          </a>
        </div>
      </main>
    </>
  )
}
